### ISSUE TITLE
BOTW Cheats: faster arrow draw is buggy

### ISSUE THREAD

**Issue by mooms06** [slashiee/cemu_graphic_packs#183]
If we use bomb arrow they will explode very close (too close: Link is hurt) if this cheat is enabled and if we aim a tree at around 10 meters.

Quick workaround: disable the cheat.

`;0x100C4F34 = .float 3; faster arrow draw (1 is default speed)`

**Comment by Crementif** [comment]
Uh, so your issue is that the default value is too high? Don't think that's an issue as it's meant to be adjusted by users, as the arrow drop will be affected by the fps you're getting. A system that's getting high fps will have a bigger arrow drop then a system with lower fps if the person is any kind of fps mod.

**Comment by mooms06** [comment]
No, the issue is that the arrows explodes at 1 meter of Link when I aim a tree a 10 meters, even with the ancient bow. 
If I aim the sky, the arrows don't explode too close.
Once disabled, no more early explosions.

**Comment by mooms06** [comment]
I've made a video showing the problem:
https://www.youtube.com/watch?v=qPQGP268yLM

I hope it's more clear now.

**Comment by Crementif** [comment]
Yeah, I understood your issue incorrectly. Reopened so that @Xalphenos can take a look and maybe judge if this helps him/should be there.

**Comment by Crementif** [comment]
Can you check is this is fixed if you use freshly downloaded static fps mods? Which packs did you have enabled?

**Comment by mooms06** [comment]
This is not fixed with latest graphic packs (2-719).
Here is the graphic packs used
![capture](https://user-images.githubusercontent.com/25405517/36344631-c20e87fa-141d-11e8-9280-2f15d42e591b.PNG)

Cemu 1.11.4b 
CemuHook 0.5.6.3
BOTW EU updated to 1.4.1 & DLC 3.0
Triple core recompiler 
Full sync at GX2DrawDone()
GPU Buffer Cache Accuracy to Low.
Windows 7 x64 Nvidia GTX 1070 with drivers 390.77 I7 6700k 16 GB of DDR4 3200.

**Comment by epigramx** [comment]
The bug that keeps on giving side-effects https://streamable.com/xdn4q

**Comment by epigramx** [comment]
I'm short of time to check this particular case now, but you can fix some bugs of this sort if you change the part of the assembler code that interests you and uses that .float instead of changing the .float globally. You can find an example of how to change a float in a particular spot in Xalphenos' fps++ code or its simplified version in static mods.

**Comment by Xalphenos** [comment]
Cheats are buggy.  This one is now less so.
