### ISSUE TITLE
Water artifacts in one location in BotW

### ISSUE THREAD

**Issue by Morph1984** [slashiee/cemu_graphic_packs#226]
I used the NVIDIA artifacts fix gfx pack and it fixed almost all the artifact issues except this one. Stumbled across this while going around Hyrule Castle
![water artifacts botw](https://user-images.githubusercontent.com/39850852/41530837-94f1ce32-731b-11e8-81f6-0f0ae467e294.png)

This is the location of that waterfall. It is close to the Korok.
![water artifacts location](https://user-images.githubusercontent.com/39850852/41530846-9a357e98-731b-11e8-8188-dccbe7950bb8.png)

**Comment by Crementif** [comment]
Thanks for reporting this! I'll get on it soon.

**Comment by Morph1984** [comment]
![rudania massive artifatcts](https://user-images.githubusercontent.com/39850852/42419403-7d0268ae-82de-11e8-8ae4-d7889ecf1486.png)
Artifacts in the eldin volcano when on Divine Beast Vah Rudania

**Comment by Crementif** [comment]
Could you provide a save at that specific point? That would help immensely!
(And I'm still planning to work on this issue, just haven't found the time
yet and I kinda hope to see this issue fixed in the next Cemu release with
the texture cache changes that might change this behaviour)

**Comment by Morph1984** [comment]
[Rudania.zip](https://github.com/slashiee/cemu_graphic_packs/files/2180086/Rudania.zip)

**Comment by Crementif** [comment]
While I was fixing a few of the artifacts that are still left, I thought I asked Exzap if this was still considered to be a Nvidia bug. Apparently, it isn't (this issue was also found by some Citra contributors who also brought this solution to Exzap with [this solution](https://github.com/citra-emu/citra/pull/3926) in a pull request). Exzap said that Nvidia just follows spec and requires the use of glTextureBarrier when you read and write to the same texture. Most drivers/gpu's just don't require it, in his words. He also said that it'll be fixed in Cemu 1.13.0.

So, about this issue or the glitch artifacts pack, I'd probably say it would be better to just wait the update out. Though, I did fix all of the ones you mentioned which I'll still commit to the repo. Thanks for reporting these!

**Comment by HeraldOD** [comment]
Not sure if this is the right place to post this, but I'm still seeing this issue in certain places.
Cemu 2.6, NVIDIA GTX 1650

<img width="1310" height="751" alt="Image" src="https://github.com/user-attachments/assets/1e6a2dcc-d407-4ffb-9614-3c0f5d3750ac" />

**Comment by Exzap** [comment]
This is fixed by the "Accurate barriers" option in the menu under Debug.

**Comment by TakariBR** [comment]
Hi, it's 2026 and still i'm having this problem. Unfortunatly I have to use OpenGL and when I do I get this kind of artifacts near waterfalls and lava. Do you guys have a solution I could use? The Accurate barriers option works only for vulkan :/
