### ISSUE TITLE
Smash No Pixel Mess Removes Effects

### ISSUE THREAD

**Issue by greensad** [slashiee/cemu_graphic_packs#255]
Super Smash Bros. for Wii U's results screen is ugly as sin without it!

**Comment by slashiee** [comment]
Pushed a WIP pack to remove the issue. This causes several effects to go missing. Need someone more experienced with shaders to fix the issue without causing effects to go missing.

**Comment by skalfate** [comment]
It cannot be solved with the shaders responsible for it. Because the same data that gets passed to the shader to process the pixel-mess texture is also responsible for the cursor in the character selection screen. So with shaders we can fix one but break the other.

It is a Cemu issue. For now, the version way of resize the texture to 1x1 is the best way.
