### ISSUE TITLE
NanoAssaultNeo_Resolution

### ISSUE THREAD

**Issue by Mored1984** [slashiee/cemu_graphic_packs#280]
**Game:** Nano Assault Neo (All Version)

**Cemu Graphic Packs:** Resolution

**Tested:** Cemu v1.4.0c

**Description:** Put below file into folder  **Cemu\graphicPacks\NanoAssaultNeo_Resolution**

[rules.txt](https://github.com/slashiee/cemu_graphic_packs/files/2612352/rules.txt)

**Code (rules.txt):**
```
[Definition]
titleIds = 0005000010110100,0005000010110600,0005000E10110100,0005000E10110600
name = "Resoluton"
path = "Nano Assault Neo/Graphics/Resolution"
description = Changes the games resolution.
version = 3

[Preset]
name = 1280x720 (Default)
$width = 1280
$height = 720
$gameWidth = 1280
$gameHeight = 720

// Performance

[Preset]
name = 256x144
$width = 256
$height = 144
$gameWidth = 1280
$gameHeight = 720

[Preset]
name = 427x240
$width = 427
$height = 240
$gameWidth = 1280
$gameHeight = 720

[Preset]
name = 640x360
$width = 640
$height = 360
$gameWidth = 1280
$gameHeight = 720

[Preset]
name = 854x480
$width = 854
$height = 480
$gameWidth = 1280
$gameHeight = 720

[Preset]
name = 960x540
$width = 960
$height = 540
$gameWidth = 1280
$gameHeight = 720

// Quality

[Preset]
name = 1600x900
$width = 1600
$height = 900
$gameWidth = 1280
$gameHeight = 720

[Preset]
name = 1920x1080
$width = 1920
$height = 1080
$gameWidth = 1280
$gameHeight = 720

[Preset]
name = 2560x1440
$width = 2560
$height = 1440
$gameWidth = 1280
$gameHeight = 720

[Preset]
name = 2732x1536
$width = 2732
$height = 1536
$gameWidth = 1280
$gameHeight = 720

[Preset]
name = 3200x1800
$width = 3200
$height = 1800
$gameWidth = 1280
$gameHeight = 720

[Preset]
name = 3840x2160
$width = 3840
$height = 2160
$gameWidth = 1280
$gameHeight = 720

[Preset]
name = 5120x2880
$width = 5120
$height = 2880
$gameWidth = 1280
$gameHeight = 720

// Enthusiast

[Preset]
name = 7680x4320
$width = 7680
$height = 4320
$gameWidth = 1280
$gameHeight = 720

[Preset]
name = 10240x5760
$width = 10240
$height = 5760
$gameWidth = 1280
$gameHeight = 720

[TextureRedefine] # Game Resolution
width = 1280
height = 720
overwriteWidth = ($width / $gameWidth) * 1280
overwriteHeight = ($height / $gameHeight) * 720
```

**Comment by skalfate** [comment]
I am not against the idea but I don't know how that can be accomplished because the thing about mass generation of all none covered games, is their title ids. That would have to be manual.

And in other news, crementif is working on automating the whole generation of the packs. Like it use to. So I suppose that is similar.

**Comment by Crementif** [comment]
Nope. I was and am still working on a new build method that would allow for filling in missing resolutions in existing graphic packs by users themselves so that we can get rid of users asking for resolutions.

I'm not very fond of the "see what sticks" pack generation, that's exactly what BatchFW tries to do and it doesn't work very well in any of the cases. https://github.com/slashiee/cemu_graphic_packs/issues/242#issuecomment-435869375

Maybe later on, I guess.

**Comment by skalfate** [comment]
Adding this pack with edits to the main repo
