### ISSUE TITLE
[NewSMBU] Shader compile error with AMD GPUs

### ISSUE THREAD

**Issue by Nezarn** [slashiee/cemu_graphic_packs#294]
This error causes the game to be black and white, also it seems to be AMD specific, error doesn't happen on my nvidia gpu.
![cemu_2018-12-07_15-22-57](https://user-images.githubusercontent.com/3817985/49653447-43a68f80-fa35-11e8-9ac2-ddfdcc7dd444.png)

`[14:22:37] Compile error in shader 50e29e8929cea348. Log:
[14:22:37] Fragment shader failed to compile with the following errors:
ERROR: 0:15: error(#206) Assigning non-constant to: const highp float
ERROR: error(#273) 1 compilation errors.  No code generated `

changing
>const float resScale = (1.0 / uf_fragCoordScale.x); 

to
>float resScale = (1.0 / uf_fragCoordScale.x);

makes it work

**Comment by Crementif** [comment]
Hm, this seems to be because the uf_fragCoordScale isn't a const here (I would assume atleast). Would be an issue likely caused by the fact that Nvidia is a little bit leaner with stuff like this.

If my assumption would be right, these other files (and possible more) would also have this issue.
https://github.com/slashiee/cemu_graphic_packs/blob/a89f270565dc51089600c7a22479ec7f65daa6ff/Resolutions/SuperMarioMaker_Resolution/37a4ec1a7dbc7391_00000000000003c9_ps.txt#L12
https://github.com/slashiee/cemu_graphic_packs/blob/a89f270565dc51089600c7a22479ec7f65daa6ff/Resolutions/NewSuperMarioBrosU_Resolution/50e29e8929cea348_00000000000003c9_ps.txt#L15

I'll fix these lines in these two packs with the solution you've mentioned, but we should be aware of this issues with other packs. @getdls Just wanted to let you be aware of this since you seem to have edited these shaders.
