### ISSUE TITLE
Breath of the Wild Anti Aliasing: Texture becomes black and white

### ISSUE THREAD

**Issue by e88z4** [slashiee/cemu_graphic_packs#317]
Hi, 

I play Zelda: Breath of the Wild using Cemu 1.15.0. My system spec is the following:

OS: Debian Sid
Mesa 19.0 Git-Development
Wine 4.0-rc4
Radeon RX580, AMDGPU driver
Kernel 4.20.0

When using the anti aliasing graphic pack, the texture colour becomes black and white. 
![botw_blackwhite](https://user-images.githubusercontent.com/15828154/50720566-7d42d880-107d-11e9-9981-ba54ab22476a.png)

This issue is specifics to the texture only. Hearts, stamina, and other on screen statistic display have colour as shown in the attachment. When I go to the menu, Link character is black and white but my inventories are coloured. 

I did a git bisect. The culprit is 

3ff3c36a11f9b832b463d394d6da43593146dc3a is the first bad commit
commit 3ff3c36a11f9b832b463d394d6da43593146dc3a
Author: Skal Fate <20464880+skalfate@users.noreply.github.com>
Date:   Sun Dec 2 22:05:15 2018 -0700

    BOTW : Fixed up Inventory Native AA and FXAA World AA (#287)
    
    * Update 0f2b9ee517917425_00000000000003c9_ps.txt
    Resolution pack Inventory AA
    
    * Update f14bb57cd5c9cb77_00000000000003c9_ps.txt
    Resolution pack World AA
    
    * Update 0f2b9ee517917425_00000000000003c9_ps.txt
    AA Pack
    
    * Update f14bb57cd5c9cb77_00000000000003c9_ps.txt
    AA Pack
    
    * Update rules.txt
    AA Pack
    
    Fixed up Inventory Native AA and FXAA World AA

Let me know if you need more information. I can do testing if needed.

**Comment by skalfate** [comment]
my bad, I will take a look right now

**Comment by skalfate** [comment]
Can you please post your cemu log here for me. The AA pack works fine on my windows 7 system so your log might have some insight as to why it fails on your side. Thank you.

**Comment by e88z4** [comment]
Attached is my cemu log. I use the bad commit from 3ff3c36a11f9b832b463d394d6da43593146dc3a (Travis235)

[log.txt](https://github.com/slashiee/cemu_graphic_packs/files/2729910/log.txt)

**Comment by e88z4** [comment]
This is the log from the previous commit.

[log.txt](https://github.com/slashiee/cemu_graphic_packs/files/2730116/log.txt)

**Comment by skalfate** [comment]
Here you go try the pack found at the end of the post.

I think the when I added .0 after say 720 in the division based on recommendation from exzap, that broke it. Which it shouldn;t. Because otherwise if the previous commit runs fine without the preprocessor "__" errors and doesnt say anything about unsupported extension then it would seem, that the only left variable. 

The same things that are a problem in the commit that says they are, are also in the previous commit. So I can only assume its the 0 division at the start of the log to be a cause of it. Whoi knows. but try the pack below and let me know.

[BreathOfTheWild_!AntiAliasing.zip](https://github.com/slashiee/cemu_graphic_packs/files/2730270/BreathOfTheWild_.AntiAliasing.zip)

**Comment by e88z4** [comment]
I tested with your zip package. It didn't resolve the issue. This is my cemu log again for your review. 
[log.txt](https://github.com/slashiee/cemu_graphic_packs/files/2730594/log.txt)

**Comment by skalfate** [comment]
But its the strangest thing though. 

That same extension is used in the commit that you said works fine for you. because in that cemu doesn't output any errors according to that log.

Anywho I am try to find a way without the extension..

**Comment by e88z4** [comment]
The latest zip package works. Thank you for resolving the issue quickly.

**Comment by skalfate** [comment]
I am glad. Thank you.
