### ISSUE TITLE
xenoblade X(jpn version) 60FPS offlinetag not recognize

### ISSUE THREAD

**Issue by yamanobe96** [slashiee/cemu_graphic_packs#322]
I'm sorry, I am in trouble! Help me!
xenoblade chickicle X's graphic packs have some things not working!
I also have an English version, but it works properly in the English version of XCX.
Although the field of view and resolution are changing properly
The offline tag and other mods have not changed at all!
60 FPS does not become static 60 FPS as if it got twice as fast!
Please help me
![ssss](https://user-images.githubusercontent.com/46581513/51073541-b5699d00-16b5-11e9-93f2-7436f1360e1a.png)

**Comment by getdls** [comment]
Attach log.txt plz

**Comment by getdls** [comment]
Reproduced, I'll look into it.

**Comment by yamanobe96** [comment]
thank you!!!!!

**Comment by getdls** [comment]
The commit patches jpn release v48 (1,02) and v16 (1.0 ) to 60 fps. Please test and close if OK. 

However since v48 keeps crashing, I recommend removing the updates and running v16 for now. No offline tag, and FOV have also been patched for v16 ( ie delete Z:\cemu_1.15.1\mlc01\usr\title\00050000\101C4D00\ )

21:9 patch doesn’t include v16, so ultra wide wont work.. I’ll get to that some day... 

Also you can’t run AA and contrasty at the same time, they modify the same shader. So the last one you check will be active.

**Comment by yamanobe96** [comment]
thank you!!
statik 60FPS became!
Offline tags are now properly hidden!
