### ISSUE TITLE
MarioKart8_3P_4P_60FPS graphic pack BUG

### ISSUE THREAD

**Issue by JonesCroatia** [slashiee/cemu_graphic_packs#357]
3 and 4 players split screen, now all works in full, true 60 fps with this mod; but now 2 player split screen works in half speed (30fps).. We need a fix for this :)

**Comment by Xalphenos** [comment]
Should be fixed now.  Let us know if it isn't.

**Comment by JonesCroatia** [comment]
Thank you very much; all split screen modes are now working 60fps, great job.

**Comment by enkelprifti98** [comment]
Thanks for this! I have a couple of questions:

1. Does 60fps affect game speed?

2. There seems to be a weird issue when using this mod along with the 4k resolution graphics pack in the dolphin shoals race where once you get out of the tunnel outside in the water fall the fps drops drastically. I don't think this has to do with my gpu because it's a 980ti. Running the 1440p graphics pack or no graphics pack at all, the issue goes away. Can you look into this please?

**Comment by Xalphenos** [comment]
1. No.  It makes all 4 quadrants refresh every frame instead of 2 quadrants refreshing every other frame.

2.  I can duplicate your issue.  It may not be fixable.  Nintendo did employ this frame skipping during 3 and 4 player for a reason after all.

**Comment by enkelprifti98** [comment]
Thanks for the response.

Regarding the issue, after looking into it in more depth, it does seem to be a GPU bottleneck after all as at 4k (2160p) GPU usage is at 99% in that area where the fps drops. Using 1800p seems to hold a stable 60fps without hurting image quality that much.

The mod is awesome! I had been waiting for this for a while, thank you so much! :)
