### ISSUE TITLE
[Tokyo Mirage Sessions♯FE]Portrait disappears after changing resolution

### ISSUE THREAD

**Issue by yamanobe96** [slashiee/cemu_graphic_packs#364]
It will be displayed like this when upgrading up without using graphic pack of resolution change
![Cemu 1 15 6c - FPS_ 30 00  NVIDIA GPU   ShaderCache_ 15735ab9   TitleId_ 00050000-101ed700  Tokyo Mirage Sessions #FE  EU v16  2019_05_13 20_26_46](https://user-images.githubusercontent.com/46581513/57618170-a50ef380-75bd-11e9-81ae-4c2b12e673ea.png)

However, if you check the graphic pack to change the resolution, the portrait will not be displayed when upgrading.
![Cemu 1 15 6c - FPS_ 30 00  NVIDIA GPU   ShaderCache_ 15735ab9   TitleId_ 00050000-101ed700  Tokyo Mirage Sessions #FE  EU v16  2019_05_13 20_24_45](https://user-images.githubusercontent.com/46581513/57618293-f61ee780-75bd-11e9-9d1f-19e70b2e28f0.png)

**Comment by iwubcode** [comment]
As described in #239 this (along with a few other bugs) is a Cemu issue and can't be solved by the graphics packs developers.

**Comment by yamanobe96** [comment]
Thank you
I would like to ask the CEMU team to respond

**Comment by Ragnar-es** [comment]
Hi, I've managed to fix the invisible portraits and intro screen textures.

The issue is caused when you go above the default 720p resolution on Cemu. This isn't really gfx pack related.

Portraits and intro background textures are exactly 1280x720 size... So I was looking at the game files and I saw another textures with smaller size that rescales good at higher resolutions (mostly backgrounds). So I tried to downsize the portrait and intro background textures by 1 pixel (1279x719), then I've reinjected the downsized textures onto the game files and repacked them and... boom! It worked.

I've made an xdelta patch for USA/EUR versions, and USA/EUR + Restoration patch versions. This is my first mod/fix ever and I don't know how to code at all so the patch is a bat file but it's pretty intuitive and easy to apply... That's the only thing I can do sadly.

Video guide with the patch: https://www.youtube.com/watch?v=6w0gIKM9j9w
