### ISSUE TITLE
[TwilightPrincessHD] FancyFX causing Hyrule Field wooden bridge disappear

### ISSUE THREAD

**Issue by indeed-a-genius** [slashiee/cemu_graphic_packs#397]
Hyrule Field wooden bridge is not visible with FancyFX enabled.

Screenshot:
![2019-09-01 22_54_31-Microsoft Edge](https://user-images.githubusercontent.com/18271528/64082269-ab5fe180-cd0c-11e9-8147-1419a4e5695b.png)

Save attached, you start directly on the bridge.
[00050000.zip](https://github.com/slashiee/cemu_graphic_packs/files/3563893/00050000.zip)

**Comment by getdls** [comment]
Should be fixed in latest commit, please test and close if ok. 

The commit should also fix return to main screen and some backgrounds. It keeps the main viewports, but most of the minor effects are back to original format, ie more banding for dust clouds and similar but less chance of late game stuff breaking..
