### ISSUE TITLE
[TPHD] When Using The Resolution Graphic Pack The Black Bars Dissapear When Pressing ZL

### ISSUE THREAD

**Issue by RianCaio** [slashiee/cemu_graphic_packs#412]
Resolution Graphic On 4K
![TPHD No Black Bars](https://user-images.githubusercontent.com/44629452/71549027-60da3300-2995-11ea-99c8-b3d190991af8.jpg)

Resolution Graphic Off 1080P Default
![TPHD Black Bars](https://user-images.githubusercontent.com/44629452/71549032-76e7f380-2995-11ea-8d69-f4adf27b3a11.jpg)

**Comment by RianCaio** [comment]
Every one of the graphic resolution to de same as the 4k

**Comment by getdls** [comment]
@RianCaio  should be fixed with https://github.com/slashiee/cemu_graphic_packs/commit/f339ad50c111f295bb33b0a3d99778e688d320da 
Please download the latest gfx pack and close issue if OK. 
<img width="497" alt="dl" src="https://user-images.githubusercontent.com/25286924/71620384-fc53e980-2bc9-11ea-9405-788b5f0da765.png">

**Comment by RianCaio** [comment]
Ok I Gonna Test Now Happy New Year

**Comment by RianCaio** [comment]
Ok Its Fixed
