### ISSUE TITLE
Hyrule Warriors 60fps mod no longer working in latest Cemu releases?

### ISSUE THREAD

**Issue by DaveACG** [slashiee/cemu_graphic_packs#435]
Can't seem to get the 60fps mod working anymore in Hyrule warriors, OpenGL or Vulkan. Started happening a few releases ago I think. My Hyrule Warriors is updated with the latest patches, was working correctly before.

**Comment by getdls** [comment]
Cemuhook is still needed for the current patch, it uses instructions that cemus patch language doesnt support yet. 

Since this question keeps cropping up here and on reddit; here's a temporary pack that works without  cemuhook
[HyruleWarriors_60FPSv4.zip](https://github.com/slashiee/cemu_graphic_packs/files/4569959/HyruleWarriors_60FPSv4.zip)

**Comment by DaveACG** [comment]
Understood, thanks very much.

**Comment by MelonSpeedruns** [comment]
Yo @getdls , could you possibly PR that v4 pack to the main repo? I'm sure a lot of people would enjoy that new pack over the old one, including me.

**Comment by Crementif** [comment]
Shouldn't go above 60FPS since the SwapInterval will only allow it to run at 60FPS, which can only be changed if you use the vsync override in the rules.txt file.

And yeah, also in favor of having this pack be pushed since it also fixes some issues the patches.txt one had apparently (not sure what the removed code did but it didn't work well, I guess). Just remove the presets in the rules.txt file.

**Comment by getdls** [comment]
Pushed zip attached zip to source. 

@MelonSpeedruns  if you're testing stuff, could you try out the one below? 
Going by the function it looks better, but I can't really tell...

[HyruleWarriors_60FPSv2.zip](https://github.com/slashiee/cemu_graphic_packs/files/4599612/HyruleWarriors_60FPSv2.zip)

**Comment by MelonSpeedruns** [comment]
I can test in a few minutes for sure. What am I testing though? :P

**Comment by getdls** [comment]
Thanks.. I tried some really stupid values just to verify, but I cant really see any change. I was hoping for some smoother camera motion.  :/

**Comment by Crementif** [comment]
Since the 60FPS mod now works, I'll close this issue. Though further discussion and experimentation can still be discussed.
