### ISSUE TITLE
[REQUEST] Add description for all packs

### ISSUE THREAD

**Issue by BennyAlex** [slashiee/cemu_graphic_packs#457]
Hello,

It would be nice to have a readme inside each mod/pack to know what it does exactly.

**Comment by slashiee** [comment]
is the description part of rules.txt not enough?

**Comment by Crementif** [comment]
The rules.txt files already have a description field in each one of them, which is also displayed in Cemu's graphic pack window whenever you click on a graphic pack. I think that they are enough in most if not all cases? If you think one of the graphic packs has a bad/confusing description, that's definitely valid feedback though.

**Comment by BennyAlex** [comment]
The problem is that many texts are to large and clipped inside cemus menu, so it would be nice to have an readme (in some cases with pictures or tables etc) on large packs (like FPS++ in botw)

**Comment by slashiee** [comment]
You need to resize the window in order to fix the description cutting off in the menu. It's an issue with Cemu, not us.

**Comment by Crementif** [comment]
Also, I just wanted to add that our version 5 graphic packs (the current ones are version 4) should be clearer due to the cleaning up and improving the user interaction, so that might help a bit too. It's a project that we're also busy with, and this isn't really something we'd consider high priority or super effective at helping the end user.
