### ISSUE TITLE
Donkey Kong Country: Tropical Freeze [ARK#01]

### ISSUE THREAD

**Issue by slashiee** [slashiee/cemu_graphic_packs#9]
Improper Water Rendering:

1080p:
![image](https://cloud.githubusercontent.com/assets/15317421/23097557/621b4ee2-f5eb-11e6-8735-ebe059ac5ab0.png)

720p (native):
![image](https://cloud.githubusercontent.com/assets/15317421/23097551/425d32b4-f5eb-11e6-9e24-aa37f1d4903f.png)

360p (half):
![image](https://cloud.githubusercontent.com/assets/15317421/23097562/7c57b71e-f5eb-11e6-912a-2ecc33ec52e1.png)

**Comment by slashiee** [comment]
Fixed as of 2e540dd

**Comment by slashiee** [comment]
Latest shader edits completely get rid of the water effect. Images from Xalphenos on Discord.

Before:
![image](https://cloud.githubusercontent.com/assets/15317421/25560287/d74e9b42-2d04-11e7-9a08-b7f4fa03268d.png)
After:
![image](https://cloud.githubusercontent.com/assets/15317421/25560289/dcb55b0c-2d04-11e7-9a96-d62c7412d519.png)

**Comment by getdls** [comment]
https://github.com/slashiee/cemu_graphic_packs/commit/175568dd28a945fb6a7da6b094f191e46f23f4bb Fixes: 

* Half transparent water
* In game and boss cut scenes
* Water during night/Dark location

Hopefully this is the last shader fix needed, I cheated around most of the game. Storm location is broken due to emulation/texture corruption. If nothing else pops up for a couple of days, i suggest closing this report. 

![tf3](https://cloud.githubusercontent.com/assets/25286924/25567792/e1887bf4-2df5-11e7-86d8-ee3afc7ea82a.png)

**Comment by slashiee** [comment]
Hey uh, @getdls is there anyway to contact you outside of GitHub? Maybe on Discord, perhaps?

**Comment by getdls** [comment]
Drop me a pm on reddit /getDls? 
I can sign up for Discord, but I'd rather avoid another time sink, esp if it's a fun one.

**Comment by getdls** [comment]
https://github.com/slashiee/cemu_graphic_packs/commit/518b74c0f9ac3c2c4e2b5e496f3d05ba3ccb901a Fixes:
Edge based AA that caused artifacts when up-resing.. been buggnin' me since I noticed it yesterday. Edges should now be clean everywhere. 
![edgecorruption](https://cloud.githubusercontent.com/assets/25286924/25584968/8ee1781c-2e98-11e7-93e1-9f40a3ebd209.png)

The design team should get a medal, my next vacation will be in the Seychelles. 
![tf3jpg](https://cloud.githubusercontent.com/assets/25286924/25585001/be9200ea-2e98-11e7-91b5-ea27b0019b7d.jpg)

**Comment by Lgnz** [comment]
I've tried to used both AA removal and the 2160p pack, this is the result:
http://imgur.com/a/OTGXs

Any idea why? I've tried different version of Cemu, always the same problem.

**Comment by getdls** [comment]
Thnx, checking. Reverted commit meanwhile

**Comment by Lgnz** [comment]
It happens too with a fresh cemu install. As soon as i use the graphic pack there's the bug.

**Comment by slashiee** [comment]
All shader issues taken care of as of 1.7.6, closing issue when 1.7.6 releases publicly.

![BotWFix](https://i.imgur.com/s7MmfuI.png)
![TFFix](https://i.imgur.com/iZkSJes.png)

**Comment by getdls** [comment]
257984d  Commit, fixes AA for 1.8 release, it replaces 518b74c.   Slashie if there's a separate 1.8 fork, feel free to move it as you see fit. 

All other water rendering is now works without separate shader edits, so this issue report can be closed.

**Comment by slashiee** [comment]
I will move those commits to a 1.8.0 branch. @getdls I'm actually gonna go against what I said earlier and just close this
